# Generated by Django 4.0.6 on 2023-10-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_options_rename_hecho_tarea_finalizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ('titulo',), 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
